# Generated by Django 3.2.8 on 2022-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211231_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
