# Generated by Django 3.2.8 on 2022-01-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_query_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='url',
            new_name='tweet_id',
        ),
    ]
