# Generated by Django 3.1.14 on 2022-01-04 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField()),
                ('replies', models.BigIntegerField()),
                ('retweets', models.BigIntegerField()),
                ('quoteTweets', models.BigIntegerField()),
                ('polarity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.query')),
            ],
        ),
    ]
